#!/usr/bin/env bash
# Merge a ref into the current branch and push it — the deterministic spine of
# workflows/merge-and-push.md. Offloads the steps that are easy to get wrong:
#   1. install husky hooks (pnpm install) so prepare-commit-msg rewrites the
#      merge subject to `chore(merge): merge <X> into <Y>` instead of a raw
#      `Merge branch ...`;
#   2. plain `git merge --no-edit <ref>` — fast-forward when possible, else a
#      merge commit (Git's default --ff). Never rebases, never squashes, never
#      passes a hand-written -m subject (which the hook would NOT rewrite).
#   3. `git push origin <branch>`.
#
# It is intentionally VERBOSE: every git/pnpm command is echoed before it runs so
# the agent can watch the install → merge → push sequence.
#
# What it deliberately does NOT do (judgment work — left to the agent):
#   - resolve merge conflicts (it stops and prints next steps);
#   - touch a dirty worktree (it refuses, so unrelated work is never clobbered);
#   - force-push, reset --hard, or fall back to `gh` on a protected-branch reject.
#
# Usage: bash .agent/skills/git-merge/tools/merge-and-push.sh <target-ref> [--no-push]
#   <target-ref>  commit SHA, local/remote branch, or tag to merge in
#   --no-push     run the merge + verification but stop before pushing
#
# Exit: 0 ok | 1 usage | 2 dirty worktree | 3 ref not found | 4 conflicts
#       (resolve manually) | 5 push rejected (e.g. protected branch)
set -euo pipefail

log() { printf '[merge-and-push] %s\n' "$*"; }
run() { printf '[merge-and-push] $ %s\n' "$*"; "$@"; }

# --- args -------------------------------------------------------------------
ref=""
push=1
for arg in "$@"; do
  case "$arg" in
    --no-push) push=0 ;;
    -*) log "error: unknown flag '$arg'"; exit 1 ;;
    *)
      if [ -n "$ref" ]; then
        log "error: more than one target ref given ('$ref' and '$arg')"
        exit 1
      fi
      ref="$arg"
      ;;
  esac
done
if [ -z "$ref" ]; then
  log "usage: merge-and-push.sh <target-ref> [--no-push]"
  exit 1
fi

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
branch="$(git rev-parse --abbrev-ref HEAD)"
log "worktree: $repo_root"
log "current branch: $branch"
log "merging in: $ref"

# --- 0. refuse to run on a dirty worktree -----------------------------------
# A merge must never silently bury unrelated uncommitted work. Untracked files
# are fine; tracked modifications / staged changes are not.
if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  log "error: worktree has uncommitted tracked changes — refusing to merge."
  log "       commit, stash, or discard them first (the agent decides what is"
  log "       safe; this tool will not clobber unrelated work). Current state:"
  git status --short
  exit 2
fi

# --- 1. ensure husky hooks are installed ------------------------------------
# core.hooksPath is relative to THIS worktree; the .husky/_ shim dir is
# gitignored and regenerated by the `prepare` script during `pnpm install`.
# Without it, prepare-commit-msg never fires and the merge lands as a raw
# `Merge branch ...` subject. NOTE: `pnpm setup:workspace` uses --ignore-scripts
# and does NOT install hooks — only `pnpm install` does.
hooks_path="$(git config core.hooksPath || true)"
log "core.hooksPath = ${hooks_path:-<unset>}"
if [ ! -x ".husky/_/prepare-commit-msg" ]; then
  log "husky shims missing (.husky/_/prepare-commit-msg) — running 'pnpm install'"
  log "to regenerate them (NOT setup:workspace, which skips the prepare script)."
  run pnpm install
fi
if [ ! -x ".husky/_/prepare-commit-msg" ]; then
  log "error: hooks still not installed after pnpm install."
  log "       The merge would land with a raw 'Merge branch ...' subject."
  log "       Fix the husky 'prepare' step, then retry."
  exit 1
fi
log "hooks ready: .husky/_/prepare-commit-msg present"

# --- 2. resolve the target ref ----------------------------------------------
if ! git rev-parse --verify --quiet "${ref}^{commit}" >/dev/null; then
  log "error: '$ref' is not a known commit/branch/tag in this repo."
  log "       If it lives on the remote, fetch it first, e.g.:"
  log "         git fetch origin $ref"
  log "         git fetch origin pull/<N>/head   # for a PR head"
  log "       then re-run with the fetched ref (e.g. origin/$ref or FETCH_HEAD)."
  exit 3
fi
target_sha="$(git rev-parse "${ref}^{commit}")"
log "resolved $ref -> $target_sha"

if git merge-base --is-ancestor "$target_sha" HEAD; then
  log "note: $ref is already an ancestor of HEAD — merge will be a no-op."
fi

# --- 3. merge (FF when possible, else a merge commit) -----------------------
# Plain `git merge --no-edit` == Git's default --ff: fast-forward when HEAD is an
# ancestor of the target, otherwise a merge commit. --no-edit keeps it
# non-interactive WITHOUT suppressing prepare-commit-msg (verified: the hook
# still fires with COMMIT_SOURCE=merge and rewrites the subject). No --no-ff, no
# --squash, no --rebase, no -m.
head_before="$(git rev-parse HEAD)"
if run git merge --no-edit "$ref"; then
  :
else
  status=$?
  if git ls-files --unmerged --error-unmatch . >/dev/null 2>&1 \
    && [ -n "$(git ls-files --unmerged)" ]; then
    log ""
    log "MERGE CONFLICTS — manual, semantic resolution required (NOT auto-resolved)."
    log "The merge is left in progress so you can resolve it. Next steps:"
    log ""
    log "  1. See what conflicted:"
    log "       git status --short            # 'UU' = both modified"
    log "       git diff --cc                 # combined conflict diff"
    log "  2. For each conflicted file, edit to keep behavior from BOTH sides."
    log "     Inspect the three versions if needed:"
    log "       git show :1:<path>  # common ancestor (base)"
    log "       git show :2:<path>  # our side  ($branch)"
    log "       git show :3:<path>  # their side ($ref)"
    log "     Remove every <<<<<<< / ======= / >>>>>>> marker."
    log "  3. Stage ONLY the resolved files:  git add <path>"
    log "  4. Confirm none remain:            git status --short  (no UU)"
    log "  5. Verify:                         git diff --check"
    log "     then the relevant package tests, e.g.:"
    log "       pnpm --filter <pkg> test && pnpm --filter <pkg> typecheck"
    log "  6. Finish WITHOUT a hand-written subject (let the hook rewrite it):"
    log "       git commit --no-edit"
    log "       git log -1 --pretty=%s        # expect: chore(merge): merge ..."
    log "  7. Then push:                      git push origin $branch"
    log ""
    log "  To bail out entirely instead: git merge --abort"
    log "Conflicted files:"
    git --no-pager diff --name-only --diff-filter=U | sed 's/^/    /'
    exit 4
  fi
  log "error: 'git merge' failed (exit $status) but no conflicts were recorded."
  log "       Inspect 'git status' above; resolve before retrying."
  exit "$status"
fi

# --- 4. report what the merge did -------------------------------------------
head_after="$(git rev-parse HEAD)"
if [ "$head_after" = "$head_before" ]; then
  log "result: nothing to do (HEAD unchanged) — already up to date."
elif [ -z "$(git rev-list -1 --merges "${head_before}..${head_after}")" ]; then
  log "result: fast-forward (no merge commit). HEAD: $head_before -> $head_after"
else
  subject="$(git log -1 --pretty=%s)"
  log "result: merge commit $head_after"
  log "        subject: $subject"
  case "$subject" in
    chore\(merge\):*) ;;
    Merge\ *)
      log "WARNING: subject is still a raw 'Merge ...' — the hook did not rewrite"
      log "         it. Re-run with hooks installed, then: git commit --amend --no-edit"
      ;;
  esac
fi

# --- 5. push (unless --no-push) ---------------------------------------------
if [ "$push" -eq 0 ]; then
  log "--no-push set: stopping before push. To push: git push origin $branch"
  exit 0
fi

log "pushing $branch to origin..."
if run git push origin "$branch"; then
  log "pushed. Remote now at:"
  git --no-pager log -1 --oneline "origin/$branch" 2>/dev/null || true
  log "done."
  exit 0
fi

# Push rejected. Do NOT force-push and do NOT fall back to gh — report and stop.
log ""
log "PUSH REJECTED. This tool will NOT force-push or route the merge through 'gh'."
log "If origin/$branch is a protected branch (e.g. GH013 'Changes must be made"
log "through a pull request'), report the exact error above to the user and stop;"
log "they decide how to proceed. Otherwise it may be a non-fast-forward — fetch"
log "and re-merge (never rebase/force):  git fetch origin && re-run this tool."
exit 5
