import type { Config } from '@docusaurus/types'
import { themes as prismThemes } from 'prism-react-renderer'
import {
  resolveDocsBaseUrl,
  resolveDocsLabCustomFields,
  resolveProductBaseUrl
} from './site-config'

const deployBase = process.env.TINYTINKERER_DEPLOY_BASE
const baseUrl = resolveDocsBaseUrl(deployBase)
const productBaseUrl = resolveProductBaseUrl(deployBase)
// Same VITE_* vars the product's own Vite builds already read at their build time
// (see apps/host/src/main.tsx, packages/app/app-browser/src/create-browser-shell-root.tsx)
// — Turbo/Vercel supplies one shared process.env to the whole `pnpm build`, so this
// Node-side Docusaurus config sees the identical values. Kept out of themeConfig
// (which is deep-merged and end-user documented) and off customFields' top level
// (reserved for arbitrary site metadata) — resolveDocsLabCustomFields gives the
// LiveLab framework its own namespaced, typed slice.
const docsLabCustomFields = resolveDocsLabCustomFields(deployBase, {
  edgeBaseUrl: process.env.VITE_EDGE_URL,
  githubClientId: process.env.VITE_GITHUB_CLIENT_ID,
  sentryDsn: process.env.VITE_SENTRY_DSN,
  sentryEnvironment: process.env.VITE_SENTRY_ENVIRONMENT
})
// This points outside the Docusaurus router (from /docs/ back to the product).
// Without these flags Docusaurus prepends its own base URL and treats the
// destination as a documentation route during link validation.
const productLink = {
  href: productBaseUrl,
  autoAddBaseUrl: false,
  target: '_top'
} as const

// Brand theme/background colors mirror packages/brand/brand-assets and the app
// shell's --bg/--panel tokens (packages/app/app-browser/src/styles.css) so the
// browser chrome (theme-color, PWA-style install prompts) matches the product.
const LIGHT_THEME_COLOR = '#f6f2ec'
const DARK_THEME_COLOR = '#1b140d'

// The favicon/apple-touch-icon/social-card files are generated by
// `pnpm generate:brand-assets` (see turbo.json's @tinytinkerer/docs#build task,
// which depends on @tinytinkerer/brand-assets#generate) and served from this
// second static directory — docs itself stays a browser-shell package with no
// @tinytinkerer/* dependency, per scripts/check-boundaries.mjs.
const brandAssetsDir = '../../packages/brand/brand-assets/assets/generated'

// The plugin ships no `types`/`exports` field in package.json, so this stays
// structurally typed rather than importing its PluginOptions type.
const searchLocalOptions = {
  hashed: true,
  language: ['en'],
  indexDocs: true,
  indexBlog: false,
  indexPages: false,
  docsRouteBasePath: '/',
  docsDir: '../../docs',
  highlightSearchTermsOnTargetPage: true,
  searchBarShortcut: true,
  searchBarShortcutHint: true,
  explicitSearchResultPath: true
}

const config: Config = {
  title: 'TinyTinkerer documentation',
  tagline: 'A Rube Goldberg machine for human-computer conversation.',
  url: 'https://tiny.nntin.xyz',
  baseUrl,
  trailingSlash: true,
  organizationName: 'NNTin',
  projectName: 'tinytinkerer',
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  staticDirectories: [brandAssetsDir],
  favicon: 'favicon.ico',
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'apple-touch-icon',
        sizes: '180x180',
        href: `${baseUrl}apple-touch-icon-180.png`
      }
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'icon',
        type: 'image/png',
        sizes: '192x192',
        href: `${baseUrl}icon-192.png`
      }
    },
    {
      tagName: 'meta',
      attributes: {
        name: 'theme-color',
        content: LIGHT_THEME_COLOR,
        media: '(prefers-color-scheme: light)'
      }
    },
    {
      tagName: 'meta',
      attributes: {
        name: 'theme-color',
        content: DARK_THEME_COLOR,
        media: '(prefers-color-scheme: dark)'
      }
    }
  ],
  markdown: {
    mermaid: true
  },
  themes: [
    '@docusaurus/theme-mermaid',
    ['@easyops-cn/docusaurus-search-local', searchLocalOptions]
  ],
  customFields: { ...docsLabCustomFields },
  presets: [
    [
      'classic',
      {
        blog: false,
        docs: {
          path: '../../docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: ({ docPath }: { docPath: string }) =>
            `https://github.com/NNTin/tinytinkerer/edit/develop/docs/${docPath}`,
          breadcrumbs: true,
          showLastUpdateTime: true
        },
        theme: {
          customCss: './src/css/custom.css'
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          ignorePatterns: ['/search']
        }
      }
    ]
  ],
  themeConfig: {
    image: 'icon-1024.png',
    metadata: [{ name: 'twitter:card', content: 'summary' }],
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'diff', 'json', 'tsx', 'yaml']
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true
      }
    },
    navbar: {
      title: 'TinyTinkerer',
      logo: {
        alt: 'TinyTinkerer mascot',
        src: 'icon-192.png'
      },
      items: [
        {
          href: 'https://github.com/NNTin/tinytinkerer',
          label: 'GitHub',
          position: 'right'
        },
        {
          ...productLink,
          label: 'Open TinyTinkerer',
          position: 'right'
        }
      ]
    },
    footer: {
      style: 'dark',
      logo: {
        alt: 'TinyTinkerer mascot',
        src: 'icon-192.png',
        width: 32,
        height: 32
      },
      links: [
        {
          title: 'Documentation',
          items: [
            { label: 'Get started', to: '/' },
            { label: 'Architecture', to: '/ARCHITECTURE' },
            { label: 'Contributing', to: '/CONTRIBUTING' },
            { label: 'Privacy', to: '/PRIVACY' }
          ]
        },
        {
          title: 'Product',
          items: [
            { ...productLink, label: 'Open the app' },
            { label: 'GitHub', href: 'https://github.com/NNTin/tinytinkerer' }
          ]
        },
        {
          title: 'Community',
          items: [
            { label: 'Instagram', href: 'https://instagram.com/thedinolino' },
            { label: 'LinkedIn', href: 'https://www.linkedin.com/in/tin-nguyen-019299279/' }
          ]
        }
      ],
      copyright: `Copyright © ${new Date().getFullYear()} TinyTinkerer contributors.`
    }
  }
}

export default config
