import { fileURLToPath } from 'node:url'
import type { Config, PluginModule } from '@docusaurus/types'
import tailwindcssPostcss from '@tailwindcss/postcss'
import { themes as prismThemes } from 'prism-react-renderer'
import {
  resolveDocsBaseUrl,
  resolveDocsLabCustomFields,
  resolveProductBaseUrl
} from './site-config'
import { documentationCorpusPlugin } from './src/docs-corpus/plugin'

const deployBase = process.env.TINYTINKERER_DEPLOY_BASE
const baseUrl = resolveDocsBaseUrl(deployBase)
const productBaseUrl = resolveProductBaseUrl(deployBase)
// Same VITE_* vars the product's own Vite builds already read at their build time
// (see apps/host/src/main.tsx, packages/app/app-browser/src/create-browser-shell-root.tsx)
// — Turbo/Vercel supplies one shared process.env to the whole `pnpm build`, so this
// Node-side Docusaurus config sees the identical values. Kept out of themeConfig
// (which is deep-merged and end-user documented) and off customFields' top level
// (reserved for arbitrary site metadata) — resolveDocsLabCustomFields gives the
// LiveLab framework its own namespaced, typed slice.
const docsLabCustomFields = resolveDocsLabCustomFields(deployBase, {
  edgeBaseUrl: process.env.VITE_EDGE_URL,
  githubClientId: process.env.VITE_GITHUB_CLIENT_ID,
  sentryDsn: process.env.VITE_SENTRY_DSN,
  sentryEnvironment: process.env.VITE_SENTRY_ENVIRONMENT
})
// This points outside the Docusaurus router (from /docs/ back to the product).
// Without these flags Docusaurus prepends its own base URL and treats the
// destination as a documentation route during link validation.
const productLink = {
  href: productBaseUrl,
  autoAddBaseUrl: false,
  target: '_top'
} as const

// Brand theme/background colors mirror packages/brand/brand-assets and the app
// shell's --bg/--panel tokens (packages/app/app-browser/src/styles.css) so the
// browser chrome (theme-color, PWA-style install prompts) matches the product.
const LIGHT_THEME_COLOR = '#f6f2ec'
const DARK_THEME_COLOR = '#1b140d'

// The favicon/apple-touch-icon/social-card files are generated by
// `pnpm generate:brand-assets` (see turbo.json's @tinytinkerer/docs#build task,
// which depends on @tinytinkerer/brand-assets#generate) and served from this
// second static directory.
const brandAssetsDir = '../../packages/brand/brand-assets/assets/generated'

// @tinytinkerer/content-mermaid loads its browser runtime via Vite's `?url`
// suffix (`mermaid/dist/mermaid.min.js?url`) so the specialized renderer can
// lazy-load it via a <script src> instead of bundling mermaid's multi-MB UMD
// build into the main chunk. Vite understands `?url` natively; webpack (which
// Docusaurus builds with) does not — without this rule, webpack falls back to
// importing the file as a plain JS module, which has no exports, so the
// resulting URL is `undefined` and the rich-content playground's/interactive
// live labs' Mermaid examples never render a real diagram (see docs/extending/
// rich-content-playground.mdx and interactive-labs.md). This rule gives `?url`
// imports the same "emit the file, give me its URL" behavior Vite provides.
const supportViteUrlSuffixImportsPlugin: PluginModule = () => ({
  name: 'support-vite-url-suffix-imports',
  configureWebpack: () => ({
    module: {
      rules: [
        {
          resourceQuery: /^\?url$/,
          type: 'asset/resource',
          generator: { filename: 'assets/vite-url-imports/[contenthash][ext]' }
        }
      ]
    },
    mergeStrategy: { 'module.rules': 'prepend' }
  })
})

// @tinytinkerer/app-browser's chat store discovers optional plugins via
// Vite's `import.meta.glob` (packages/app/app-browser/src/plugins/registry.ts),
// another Vite-only build-time feature webpack has no equivalent for. Unlike
// the `?url` case above this isn't confined to one specialized renderer:
// `chat-store.ts` imports `loadPluginModules` directly, so EVERY live lab
// that touches `useChatStore` (every one built so far, including issue #452's
// Pixel Agents lab) pulls this in and crashes at runtime ("...glob is not a
// function") the instant the module evaluates — whether or not the lab cares
// about plugins at all. Docs has no `packages/plugins/*` of its own to
// discover anyway, so aliasing the whole module to a "no plugins" stub
// (live-lab/plugin-registry-stub.ts) is correct behavior, not a workaround.
const appBrowserPluginRegistryPath = fileURLToPath(
  new URL('../../packages/app/app-browser/src/plugins/registry.ts', import.meta.url)
)
const pluginRegistryStubPath = fileURLToPath(
  new URL('./src/live-lab/plugin-registry-stub.ts', import.meta.url)
)
const stubAppBrowserPluginDiscoveryPlugin: PluginModule = () => ({
  name: 'stub-app-browser-plugin-discovery',
  configureWebpack: () => ({
    resolve: {
      alias: {
        [appBrowserPluginRegistryPath]: pluginRegistryStubPath
      }
    }
  })
})

// The live-lab framework embeds the REAL ChatApp/PixelAgentsStage components
// (see interactive-labs.md), styled with Tailwind utility classes — but every
// TinyTinkerer app that renders them (host, canvas, mermaid, ide, pixel-agents)
// generates those utilities itself, via its own `@tailwindcss/vite` build
// scanning `packages/` (e.g. apps/host/src/index.css's `@source
// "../../../packages"`). Docusaurus builds with webpack, which never ran that
// scan, so none of those classes have ever had matching CSS here. This wires
// `@tailwindcss/postcss` into Docusaurus's existing postcss-loader pipeline —
// the SAME source-of-truth scan (src/css/tailwind.css's `@source` points at
// the same `packages/`), not a hand-copied stylesheet, so the generated
// utilities can't drift from what those apps' own builds produce.
const enableTailwindPostCssPlugin: PluginModule = () => ({
  name: 'enable-tailwind-postcss',
  configurePostCss: (options) => {
    options.plugins.push(tailwindcssPostcss())
    return options
  }
})

// The Pixel Agents lab (issue #452) embeds the SAME prepared upstream bundle
// `apps/pixel-agents` already builds (`pnpm -w prepare:pixel-agents`, run by
// this package's own dev/build scripts) rather than fetching/building a
// second copy — composed by path, the same way a host compositor composes
// another app's build output (see scripts/check-boundaries.mjs). This
// directory contains exactly one `upstream/` subfolder, so Docusaurus serves
// its contents at `${baseUrl}upstream/**` — an absolute path that resolves
// correctly regardless of which nested docs route embeds the lab, unlike a
// path resolved relative to the current page (see live-lab/pixel-agents/
// upstream-url.ts).
const pixelAgentsUpstreamDir = '../pixel-agents/generated'

// The plugin ships no `types`/`exports` field in package.json, so this stays
// structurally typed rather than importing its PluginOptions type.
const searchLocalOptions = {
  hashed: true,
  language: ['en'],
  indexDocs: true,
  indexBlog: false,
  indexPages: false,
  docsRouteBasePath: '/',
  docsDir: '../../docs',
  highlightSearchTermsOnTargetPage: true,
  searchBarShortcut: true,
  searchBarShortcutHint: true,
  explicitSearchResultPath: true
}

const config: Config = {
  title: 'TinyTinkerer documentation',
  tagline: 'A Rube Goldberg machine for human-computer conversation.',
  url: 'https://tiny.nntin.xyz',
  baseUrl,
  trailingSlash: true,
  organizationName: 'NNTin',
  projectName: 'tinytinkerer',
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  staticDirectories: [brandAssetsDir, pixelAgentsUpstreamDir],
  favicon: 'favicon.ico',
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'apple-touch-icon',
        sizes: '180x180',
        href: `${baseUrl}apple-touch-icon-180.png`
      }
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'icon',
        type: 'image/png',
        sizes: '192x192',
        href: `${baseUrl}icon-192.png`
      }
    },
    {
      tagName: 'meta',
      attributes: {
        name: 'theme-color',
        content: LIGHT_THEME_COLOR,
        media: '(prefers-color-scheme: light)'
      }
    },
    {
      tagName: 'meta',
      attributes: {
        name: 'theme-color',
        content: DARK_THEME_COLOR,
        media: '(prefers-color-scheme: dark)'
      }
    }
  ],
  markdown: {
    mermaid: true
  },
  themes: [
    '@docusaurus/theme-mermaid',
    ['@easyops-cn/docusaurus-search-local', searchLocalOptions]
  ],
  plugins: [
    documentationCorpusPlugin,
    supportViteUrlSuffixImportsPlugin,
    stubAppBrowserPluginDiscoveryPlugin,
    enableTailwindPostCssPlugin
  ],
  customFields: { ...docsLabCustomFields },
  presets: [
    [
      'classic',
      {
        blog: false,
        docs: {
          path: '../../docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: ({ docPath }: { docPath: string }) =>
            `https://github.com/NNTin/tinytinkerer/edit/develop/docs/${docPath}`,
          breadcrumbs: true,
          showLastUpdateTime: true
        },
        theme: {
          customCss: './src/css/custom.css'
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          ignorePatterns: ['/search']
        }
      }
    ]
  ],
  themeConfig: {
    image: 'icon-1024.png',
    metadata: [{ name: 'twitter:card', content: 'summary' }],
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'diff', 'json', 'tsx', 'yaml']
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: true
      }
    },
    navbar: {
      title: 'TinyTinkerer',
      logo: {
        alt: 'TinyTinkerer mascot',
        src: 'icon-192.png'
      },
      items: [
        {
          href: 'https://github.com/NNTin/tinytinkerer',
          label: 'GitHub',
          position: 'right'
        },
        {
          ...productLink,
          label: 'Open TinyTinkerer',
          position: 'right'
        }
      ]
    },
    footer: {
      style: 'dark',
      logo: {
        alt: 'TinyTinkerer mascot',
        src: 'icon-192.png',
        width: 32,
        height: 32
      },
      links: [
        {
          title: 'Documentation',
          items: [
            { label: 'Get started', to: '/' },
            { label: 'Architecture', to: '/architecture' },
            { label: 'Contributing', to: '/contributing' },
            { label: 'Privacy', to: '/overview/PRIVACY' }
          ]
        },
        {
          title: 'Product',
          items: [
            { ...productLink, label: 'Open the app' },
            { label: 'GitHub', href: 'https://github.com/NNTin/tinytinkerer' }
          ]
        },
        {
          title: 'Community',
          items: [
            { label: 'Instagram', href: 'https://instagram.com/thedinolino' },
            { label: 'LinkedIn', href: 'https://www.linkedin.com/in/tin-nguyen-019299279/' }
          ]
        }
      ],
      copyright: `Copyright © ${new Date().getFullYear()} TinyTinkerer contributors.`
    }
  }
}

export default config
