// packages/types is a compatibility shim — import from @tinytinkerer/contracts directly.
// Planned for removal once all consumers are migrated.
export type {
  EventType,
  SearchResult,
  PlanComplexity,
  PlanStep,
  ExecutionPlan,
  UserMessageEvent,
  PlanningStartedEvent,
  PlanGeneratedEvent,
  ExecutionStartedEvent,
  ExecutionStepStartedEvent,
  ToolCallStartedEvent,
  ToolCallCompletedEvent,
  ToolCallFailedEvent,
  ExecutionStepCompletedEvent,
  ExecutionCompletedEvent,
  RateLimitWaitingEvent,
  RateLimitRecoveredEvent,
  RateLimitCancelledEvent,
  AssistantChunkEvent,
  AssistantDoneEvent,
  ErrorEvent,
  SystemEvent,
  ChatEvent,
  ServiceStatus,
  SystemStatus,
} from '@tinytinkerer/contracts'
