import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { collectDependencyLicenses } from './lib/dependency-licenses.mjs'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')

// The Markdown notices file is a build artifact (uploaded by the Compliance
// workflow); it is intentionally not committed (see .gitignore).
const markdownPath = join(
  rootDir,
  process.env.NOTICES_OUTPUT ?? join('dist', 'compliance', 'THIRD_PARTY_NOTICES.md')
)

// The same content is embedded in a generated module so the app can show it in
// the Settings dialog, mirroring how the privacy policy is surfaced. Also
// gitignored (via **/*.generated.ts) and regenerated by the build pipeline.
const modulePath = join(
  rootDir,
  'packages',
  'brand',
  'brand-assets',
  'src',
  'third-party-notices.generated.ts'
)

const buildMarkdown = (dependencies) => {
  // Group packages by license so the attribution reads cleanly.
  /** @type {Map<string, typeof dependencies>} */
  const byLicense = new Map()
  for (const dep of dependencies) {
    const bucket = byLicense.get(dep.license) ?? []
    bucket.push(dep)
    byLicense.set(dep.license, bucket)
  }

  const licenses = [...byLicense.keys()].sort((a, b) => a.localeCompare(b))

  const lines = [
    '# Third-Party Notices',
    '',
    'This application is built with the open-source software listed below, grouped',
    'by license.',
    ''
  ]

  for (const license of licenses) {
    const packages = byLicense.get(license) ?? []
    lines.push(`## ${license}`, '')
    for (const dep of packages) {
      const version = dep.version ? `@${dep.version}` : ''
      const homepage = dep.homepage ? ` — ${dep.homepage}` : ''
      const author = dep.author ? ` (by ${dep.author})` : ''
      lines.push(`- **${dep.name}${version}**${author}${homepage}`)
    }
    lines.push('')
  }

  // No timestamp: the output is embedded in the frontend bundle, so it must be
  // deterministic for a given dependency tree (stable hashes, no build churn).
  return `${lines.join('\n').trimEnd()}\n`
}

const main = () => {
  const dependencies = collectDependencyLicenses()
  const markdown = buildMarkdown(dependencies)

  mkdirSync(dirname(markdownPath), { recursive: true })
  writeFileSync(markdownPath, markdown)

  mkdirSync(dirname(modulePath), { recursive: true })
  const module = `// AUTO-GENERATED by scripts/generate-notices.mjs — do not edit.\nexport const THIRD_PARTY_NOTICES = ${JSON.stringify(markdown)}\n`
  writeFileSync(modulePath, module)

  console.log(
    `Generated third-party notices for ${dependencies.length} dependencies:\n  - ${markdownPath}\n  - ${modulePath}`
  )
}

main()
