/**
 * The documents these tests resolve against are **this site's own**, not
 * invented ones.
 *
 * That is the point: a fictional corpus cannot disagree with reality, so it
 * cannot catch a rule that is wrong for the real site. (An earlier revision
 * asserted a landing-page policy against a fabricated `index` ref while the
 * real landing document is `documentation-home`; nothing failed.)
 *
 * Every field below is copied from the built manifest
 * (`build/assets/docs-corpus/manifest.v1.<hash>.json`), and `assertFixtureStillMatchesSite`
 * pins the authored frontmatter each one depends on, in the same spirit as
 * `apps/docs/tests/information-architecture.test.ts`. Renaming a real document
 * fails that guard instead of quietly making these fixtures fictional again.
 *
 * Two cases have no real equivalent on this site and are therefore synthetic;
 * both are marked as such where they are declared.
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { expect, it } from 'vitest'
import type { DocumentationCorpusManifestEntry } from '@tinytinkerer/app-browser/documentation-corpus'

/**
 * This site's real configuration: `resolveDocsBaseUrl` in
 * apps/docs/site-config.ts returns `/docs/`, and docusaurus.config.ts sets
 * `trailingSlash: true` with the docs plugin at `routeBasePath: '/'`.
 */
export const SITE_CONFIG = { baseUrl: '/docs/', trailingSlash: true }

const entry = (
  overrides: Partial<DocumentationCorpusManifestEntry> = {}
): DocumentationCorpusManifestEntry => ({
  ref: 'architecture/packages-concept',
  version: 'current',
  versionPath: '/docs/',
  isLast: true,
  title: 'Packages Concept',
  permalink: '/docs/architecture/packages-concept/',
  source: '@site/../../docs/architecture/packages-concept.md',
  contentHash: 'c'.repeat(64),
  artifactHash: 'a'.repeat(64),
  unlisted: false,
  artifact: '/docs/assets/docs-corpus/documents/current-architecture-packages-concept.abc.def.json',
  characterCount: 4321,
  sectionCount: 9,
  ...overrides
})

/** `docs/architecture/packages-concept.md` — an ordinary authored document. */
export const CANONICAL_DOCUMENT = entry()

/**
 * `docs/index.mdx` — the docs landing route, which this site authors
 * (`id: documentation-home`, `slug: /`) rather than generating.
 */
const LANDING_DOCUMENT = entry({
  ref: 'documentation-home',
  title: 'TinyTinkerer documentation',
  permalink: '/docs/',
  source: '@site/../../docs/index.mdx'
})

/** `docs/updates/PRIVACY-UPDATE.md` — authored `unlisted: true`, still routed. */
const UNLISTED_DOCUMENT = entry({
  ref: 'updates/PRIVACY-UPDATE',
  title: 'Privacy policy updated',
  permalink: '/docs/updates/PRIVACY-UPDATE/',
  source: '@site/../../docs/updates/PRIVACY-UPDATE.md',
  unlisted: true
})

/**
 * Synthetic: this site loads no versioned docs, so there is no real historical
 * entry to copy. The shape is Docusaurus', and #476 must hold for a site that
 * does version its docs.
 */
const HISTORICAL_DOCUMENT = entry({
  version: '1.0',
  versionPath: '/docs/1.0/',
  isLast: false,
  title: 'Packages Concept (1.0)',
  permalink: '/docs/1.0/architecture/packages-concept/'
})

/**
 * Synthetic: a Docusaurus-generated category index, which carries its slug (and
 * so a leading slash) as its id. See `siteGlobalData` for why this site has
 * none of its own.
 */
export const GENERATED_INDEX_ID = '/category/architecture'
export const GENERATED_INDEX_PATH = '/docs/category/architecture/'

export const SITE_DOCUMENTS: DocumentationCorpusManifestEntry[] = [
  CANONICAL_DOCUMENT,
  LANDING_DOCUMENT,
  UNLISTED_DOCUMENT,
  HISTORICAL_DOCUMENT
]

/**
 * Mirrors what `toGlobalDataVersion` publishes for this site: authored docs,
 * unlisted docs (still routed, still listed), and — synthetically — a generated
 * category index carrying its slug as an id. Drafts are absent by construction;
 * Docusaurus keeps them in `draftIds`, never in `docs`.
 *
 * The site's own sidebar produces no category route (`sidebars.ts` is a single
 * `autogenerated` entry with no `link: { type: 'generated-index' }`, and the
 * build emits no `category/` directory), so that one entry is the deliberate
 * exception to "real documents only" — it exists to cover a branch this site
 * does not currently exercise.
 */
export const siteGlobalData = (documents: DocumentationCorpusManifestEntry[] = SITE_DOCUMENTS) => ({
  path: '/docs/',
  breadcrumbs: true,
  versions: [
    {
      name: 'current',
      label: 'Next',
      isLast: true,
      path: '/docs/',
      mainDocId: 'documentation-home',
      draftIds: [],
      docs: [
        ...documents
          .filter((document) => document.isLast)
          .map((document) => ({
            id: document.ref,
            path: document.permalink,
            ...(document.unlisted ? { unlisted: true } : {})
          })),
        { id: GENERATED_INDEX_ID, path: GENERATED_INDEX_PATH }
      ]
    },
    {
      name: '1.0',
      label: '1.0',
      isLast: false,
      path: '/docs/1.0/',
      mainDocId: 'documentation-home',
      draftIds: [],
      docs: documents
        .filter((document) => !document.isLast)
        .map((document) => ({ id: document.ref, path: document.permalink }))
    }
  ]
})

/**
 * Resolved from the workspace root (`apps/docs`) rather than `import.meta.url`,
 * matching docs-corpus/__tests__/normalize.test.ts — Vite rewrites the module
 * URL to a `/@fs/...` form that `fileURLToPath` cannot turn back into a path.
 */
const readAuthoredSource = (relativePath: string): string =>
  readFileSync(resolve(process.cwd(), '../../docs', relativePath), 'utf8')

/**
 * Registers the guard that keeps the fixtures above honest. Call it from one
 * `describe` per suite that uses them: `readFileSync` throws if a document has
 * been renamed or moved, and the frontmatter assertions catch the subtler case
 * where the file survives but the identity these fixtures encode does not.
 *
 * Deliberately checks the *authored source*, not the built manifest — a build
 * artifact is not always present, and frontmatter is what decides these ids.
 */
export const assertFixtureStillMatchesSite = (): void => {
  it('is built from documents this site really authors', () => {
    // `id:` is what makes the landing route `documentation-home` rather than
    // the path-derived `index`, and `slug: /` is what puts it at `/docs/`.
    const landing = readAuthoredSource('index.mdx')
    expect(landing).toMatch(/^id: documentation-home$/m)
    expect(landing).toMatch(/^slug: \/$/m)

    // Authored visibility, which #474 reads instead of the derived metadata
    // flag Docusaurus neutralizes during `docusaurus start`.
    expect(readAuthoredSource('updates/PRIVACY-UPDATE.md')).toMatch(/^unlisted: true$/m)

    // No `id:` of its own, so its ref is the path — the ordinary case.
    expect(readAuthoredSource('architecture/packages-concept.md')).not.toMatch(/^id:/m)
  })
}
